services:
    http-server:
        image: nginx:latest
    app:
        image: myapp:latest
    watchtower:
        image: containrrr/watchtower
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        command: --interval 7200
